  trigger:
    branches:
      include:
        - master

  pr:
    branches:
      exclude:
        - '*'

  name: pr.$(prId)-$(prIteration)

  variables:
  - group: Code_Signing_Certificate_2023_2026
  - name: prId
    value: $[coalesce(variables['System.PullRequest.PullRequestId'], '000')]
  - name: prIteration
    value: $[counter(variables['prId'], 1)]
  - name: buildConfiguration
    value: Release

  stages:
  - stage: BuildAndPublish
    condition: succeeded()
    jobs: 
    - job: BuildAndSign
      pool:
        vmImage: 'windows-latest'

      steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          versionSpec: '9.x'

      - checkout: self
        persistCredentials: true
        fetchDepth: 0

      - task: GitVersion@5
        inputs:
          runtime: 'core'
          versionSpec: '5.x'
        name: gitVersion

      - task: DownloadSecureFile@1
        name: cert
        inputs:
          secureFile: 'code-signing-certificate-2023-2026.pfx'

      #- script: dotnet restore
      #  displayName: 'Restore Dependencies'

      # - script: >
      #     dotnet build ./Infragistics.QueryBuilder.Executor.csproj
      #     --configuration $(buildConfiguration)
      #     --no-restore
      #   displayName: 'Build Project'
      
      #- powershell: |
      #    Write-Host "Building project and forcing output path..."
      #    dotnet build ./Infragistics.QueryBuilder.Executor.csproj `
      #      --configuration $(buildConfiguration) `
      #      --no-restore
      #  displayName: 'Build Project'
      - task: DotNetCoreCLI@2
        displayName: Build project
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          workingDirectory: '$(Build.SourcesDirectory)'

      - powershell: |
          $outputDir = "$(Build.SourcesDirectory)\bin\$(buildConfiguration)\net9.0"
          Write-Host "Listing contents of: $outputDir"
          if (-Not (Test-Path $outputDir)) {
            Write-Error "Output folder not found: $outputDir"
            exit 1
          }
          Get-ChildItem $outputDir -Recurse | ForEach-Object {
            Write-Host $_.FullName
          }
        displayName: 'Debug: List build output contents'

      - powershell: |
          $dllFolder = "$(Build.SourcesDirectory)\bin\$(buildConfiguration)\net9.0"
          Write-Host "Signing DLLs in folder: $dllFolder"
          if (-Not (Test-Path $dllFolder)) {
              Write-Error "Folder does not exist: $dllFolder"
              exit 1
          }
          
          Write-Host "Trying to use the latest version of the Windows Kit and the signtool from it"
          $signtoolPath = Get-ChildItem -Path "${env:ProgramFiles(x86)}\Windows Kits\10\bin" -Recurse -Filter signtool.exe |
              Where-Object { $_.FullName -match 'x64\\signtool\.exe$' } |
              Select-Object -First 1

          if (-not $signtoolPath) {
              Write-Error "signtool.exe not found in Windows Kits"
              exit 1
          }

          Write-Host "Using signtool at: $($signtoolPath.FullName)"

          $dllFiles = Get-ChildItem -Path $dllFolder -Filter *.dll -Recurse
          foreach ($dll in $dllFiles) {
            Write-Host "Signing $($dll.FullName)..."
            & $signtoolPath.FullName sign /f $(cert.secureFilePath) /p $env:CERT_PASS /tr $(SigningCertificateTimestampUrl) /td sha256 /fd sha256 $dll.FullName

            if ($LASTEXITCODE -ne 0) {
              Write-Error "Signing failed for $($dll.FullName)"
              exit 1
            }
          }
        displayName: 'Sign all DLL files with PFX certificate'
        env:
          CERT_PASS: $(SigningCertificatePassword)

      - powershell: |
          $packageOutputDir = "$(Build.ArtifactStagingDirectory)\nuget"
          $packageVersion = "$(GitVersion.NuGetVersionV2)"

          Write-Host "Packing project from existing build output..."
          dotnet pack ./Infragistics.QueryBuilder.Executor.csproj `
            --no-build `
            --configuration $(buildConfiguration) `
            -p:PackageVersion=$packageVersion `
            -o $packageOutputDir

          if ($LASTEXITCODE -ne 0) {
            Write-Error "dotnet pack failed"
            exit 1
          } 
        displayName: 'Pack NuGet Package using PowerShell'

      - task: PowerShell@2 
        displayName: 'Sign NuGet package'
        env:
          CERT_PASS: $(SigningCertificatePassword)
        inputs:
          targetType: 'inline'
          script: |
            nuget.exe sign $(Build.ArtifactStagingDirectory)\nuget\*.nupkg -CertificatePath $(cert.secureFilePath) -CertificatePassword $env:CERT_PASS -Timestamper $(SigningCertificateTimestampUrl)

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget'
          ArtifactName: 'NuGetPackage'
          publishLocation: 'Container'
        displayName: 'Publish nuget Package as Build Artifact'

      # - task: NuGetCommand@2
      #   inputs:
      #     command: 'push'
      #     packagesToPush: '$(Build.ArtifactStagingDirectory)/nuget/*.nupkg'
      #     nuGetFeedType: 'external'
      #     publishFeedCredentials: 'NuGet'
      #   displayName: 'Publish to NuGet.org'
